### ISSUE TITLE
seahub_settings.py: Unknown system variable 'storage_engine'

### ISSUE THREAD

**Issue by corny** [ginsys/ansible-role-seafile#17]
As of MySQL 5.6.3 the variable `storage_engine` has been renamed to `default_storage_engine`:
https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_default_storage_engine

On Ubuntu 16.04 with MariaDB 10.0.27 the variable `storage_engine` is unknown and the role fails.

**Comment by srvg** [comment]
Thanks for your report. It seems that engine specific part is left out in the configuration nowadays: https://github.com/haiwen/seafile/blob/master/scripts/setup-seafile-mysql.py#L990 so leaving that out should fix this.

**Comment by srvg** [comment]
@corny can you confirm 3507f812a7456c0365fc55c0b93012cf3d7515f2 fixes your issue?

You can test that by checking out PR #18 as a branch:

`git fetch origin pull/18/head:PR/origin/18 && git checkout PR/origin/18`

and testing that.

**Comment by corny** [comment]
@srvg Thanks for the quick response. Removing the `OPTIONS` fixes the issue. Please merge the PR.

**Comment by srvg** [comment]
Thanks!
