### ISSUE TITLE
404 for bintray

### ISSUE THREAD

**Issue by tivvit** [ginsys/ansible-role-seafile#25]
https://github.com/ginsys/ansible-role-seafile/blob/3507f812a7456c0365fc55c0b93012cf3d7515f2/defaults/main.yml#L7 
 results in https://bintray.com/artifact/download/seafile-org/seafile/seafile-server_6.0.4_x86-64.tar.gz which return 404

**Comment by srvg** [comment]
solved by @corny in #27 - update to v6.2
