### ISSUE TITLE
Add sudo to packages dependencies

### ISSUE THREAD

**Issue by JocelynDelalande** [ginsys/ansible-role-seafile#3]
As sudo is used in playbooks, it should IMHO be installed via the playbook (see `DEPENDENCY_PACKAGES_RPM` and `DEPENDENCY_PACKAGES_APT`).

**Comment by JocelynDelalande** [comment]
Hi @srvg 

> It occurs to me that using the sudo capability within ansible, needs more than just installing the package. ansible+sudo is a specific configuration that needs to be done before being able to use ansible.

Well, depends on your setup & usage. Here, you are using sudo not to act as root but to act as a specific user.

If ansible operations are done with root (or highly privilegied user) (which is common), installing sudo is enough.

> On the other hand, it wouldn't harm I guess, to add sudo to the dependency 
list, it would just be - at least to me - a bit weird and unusual to handle it here.

Can't speak for others, but for the way I use ansible, it makes sense to add sudo as a dependency

> Can you follow me, and possibly understand my point of view?

Sure, thanks for your comprehensive and fast answer :-).

**Comment by srvg** [comment]
Up until now, I have always thought, 'sudo' is part of any default installation, at least in Ubuntu which is what I use primarily. But I understand this can be a thing, so I will make this ticket a feature request I will take into account.
