### ISSUE TITLE
Supported OSes?

### ISSUE THREAD

**Issue by wizonesolutions** [ginsys/ansible-role-seafile#4]
Or: does this work on CentOS 6? :)

**Comment by srvg** [comment]
Sorry for the late response, seems I looked over this ticket.

I initially tested this role with Centos. I can't recall the exact version i used back then (Redhat/Centos is not my usual distro) but I'm pretty sure it was tested with v6, so yes.

It's also not very straightforward to add supported versions of supported distributions. Not sure how I could handle that.
