### ISSUE TITLE
Use password lookup to generate keys.

### ISSUE THREAD

**Issue by JocelynDelalande** [ginsys/ansible-role-seafile#6]
Crypto keys are regenerated each time you run the playbook, which is quite disaster-prone.

I just discovered the [ansible password lookup](http://docs.ansible.com/playbooks_lookups.html#the-password-lookup) that might be used to avoid that.

**Comment by srvg** [comment]
Hi @JocelynDelalande 
Can you elaborate on which part of this role you are talking about?

Is this about this task in `tasks/preconfigure.yml`?
``` 43 - name:                 generate seahub_settings secret key```

**Comment by JocelynDelalande** [comment]
Hi @srvg Yep, I was speaking about that. But maybe that behaviour changed since, I haven't tested with latest version of your role.

**Comment by srvg** [comment]
Yes, the key pijnt is that task contains a creates=.. , so it will only run if the file with the key does not exist yet. The idea is of course, that file is part of the data you need to backup.

I'm aware of the password lookup plugins, but I'm not a fan of them, as those change things in your local setup, which is versioned.

Either way, this is a task that was made early, I dont think anything changed how this behaves.

One of the difficulties with this seafile role, is that I have to recreate everything that happens with the default install scripts, which makes assumption that are not always easy to translate into a configuration management thing.

I'm stil not sure what you meant by "Crypto keys are regenerated each time you run the playbook, which is quite disaster-prone." As far as I can tell, this is not the case. Did you encounter a practical problem with this?

**Comment by JocelynDelalande** [comment]
> I'm stil not sure what you meant by "Crypto keys are regenerated each time you run the playbook, which is quite disaster-prone." As far as I can tell, this is not the case. Did you encounter a practical problem with this?

Yup, but can't reproduce at the moment, so closing, sorry for the noise and thanks for your answers :)
