### ISSUE TITLE
provision media folders error

### ISSUE THREAD

**Issue by lexrus** [ginsys/ansible-role-seafile#8]
![screen shot 2015-05-14 at 2 53 12 pm](https://cloud.githubusercontent.com/assets/219689/7627330/fce398f8-fa48-11e4-9e51-f8c99a547523.png)

**Comment by lexrus** [comment]
I'm doing a fresh install of the latest stable release 4.1.2 on a Debian Wheezy server with Ansible 1.9.1.

**Comment by srvg** [comment]
This is fixed in role version 4.1.2
